<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title><c:choose><c:when test="${mode == 'edit'}">Edit Tender</c:when><c:otherwise>Create Tender</c:otherwise></c:choose> | ProcureGov</title>
        <link rel="icon" type="image/x-icon" href="${pageContext.request.contextPath}/images/images.png"/>
        <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"/>
    </head>
    <body>

        <%@ include file="/WEB-INF/views/common/navbar.jsp" %>

        <div class="page-content">
            <div class="container">

                <div class="breadcrumb">
                    <a href="${pageContext.request.contextPath}/officer/dashboard">Dashboard</a>
                    <span>›</span>
                    <a href="${pageContext.request.contextPath}/officer/tenders">Tenders</a>
                    <span>›</span>
                    <span><c:choose><c:when test="${mode == 'edit'}">Edit Tender</c:when><c:otherwise>New Tender</c:otherwise></c:choose></span>
                </div>

                <div class="page-header">
                    <div>
                        <span class="section-label">Module 2 — Tender Management</span>
                        <h1 class="page-title">
                            <c:choose>
                                <c:when test="${mode == 'edit'}">Edit Tender</c:when>
                                <c:otherwise>Create New Tender</c:otherwise>
                            </c:choose>
                        </h1>
                    </div>
                </div>

                <c:if test="${not empty errorMsg}">
                    <div class="alert alert-danger">${errorMsg}</div>
                </c:if>

                <%-- Client-side PDF size error — shown by JS before form submits --%>
                <div class="alert alert-danger" id="pdfSizeError" style="display:none;">
                    <svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"
                         viewBox="0 0 24 24" style="flex-shrink:0;">
                        <circle cx="12" cy="12" r="10"/>
                        <line x1="12" y1="8" x2="12" y2="12"/>
                        <line x1="12" y1="16" x2="12.01" y2="16"/>
                    </svg>
                    <div>
                        <strong>File Too Large</strong><br/>
                        <span id="pdfSizeMsg"></span>
                    </div>
                </div>

                <div class="form-card">
                    <form
                        action="${pageContext.request.contextPath}/officer/tender/<c:choose><c:when test="${mode == 'edit'}">edit</c:when><c:otherwise>create</c:otherwise></c:choose>"
                        method="POST"
                        enctype="multipart/form-data"
                        novalidate
                        id="tenderForm">

                        <c:if test="${mode == 'edit'}">
                            <input type="hidden" name="tenderId" value="${tender.tenderId}"/>
                        </c:if>

                        <!-- Reference No (system-generated, read-only) -->
                        <div class="form-group">
                            <label class="form-label">Reference Number</label>
                            <input
                                class="form-input"
                                type="text"
                                value="<c:choose><c:when test="${mode == 'edit'}">${tender.referenceNo}</c:when><c:otherwise>${referenceNo}</c:otherwise></c:choose>"
                                disabled
                                style="opacity:0.6; cursor:not-allowed;"/>
                            <span class="form-hint">Auto-generated by the system in format MPW-YYYY-NNNN.</span>
                        </div>

                        <!-- Title -->
                        <div class="form-group">
                            <label class="form-label" for="title">Tender Title <span style="color:var(--clr-danger)">*</span></label>
                            <input
                                class="form-input"
                                type="text"
                                id="title"
                                name="title"
                                placeholder="e.g. Rehabilitation of Maseru-Mazenod Road"
                                value="<c:choose><c:when test="${mode == 'edit'}">${tender.title}</c:when><c:otherwise>${param.title}</c:otherwise></c:choose>"
                                required maxlength="300"/>
                        </div>

                        <!-- Category -->
                        <div class="form-group">
                            <label class="form-label" for="category">Category <span style="color:var(--clr-danger)">*</span></label>
                            <select class="form-select" id="category" name="category" required>
                                <option value="">— Select a category —</option>
                                <c:forEach var="cat" items="${categories}">
                                    <option value="${cat.name()}"
                                        <c:if test="${mode == 'edit' && tender.category == cat}">selected</c:if>
                                        <c:if test="${mode == 'create' && param.category == cat.name()}">selected</c:if>
                                    >${cat.label}</option>
                                </c:forEach>
                            </select>
                        </div>

                        <!-- Description -->
                        <div class="form-group">
                            <label class="form-label" for="description">Description <span style="color:var(--clr-danger)">*</span></label>
                            <textarea
                                class="form-input"
                                id="description"
                                name="description"
                                rows="5"
                                placeholder="Provide full scope of work, technical specifications, and requirements..."
                                required
                                style="resize:vertical; min-height:120px;"
                            ><c:choose><c:when test="${mode == 'edit'}">${tender.description}</c:when><c:otherwise>${param.description}</c:otherwise></c:choose></textarea>
                        </div>

                        <!-- Estimated Value + Closing Date -->
                        <div class="form-row">
                            <div class="form-group">
                                <label class="form-label" for="estimatedValue">Estimated Value (Maloti) <span style="color:var(--clr-danger)">*</span></label>
                                <div class="input-wrapper">
                                    <span class="input-icon" style="font-size:0.78rem; font-weight:600; color:var(--clr-text-muted); width:auto; left:14px;">M</span>
                                    <input
                                        class="form-input form-input--icon"
                                        type="number"
                                        id="estimatedValue"
                                        name="estimatedValue"
                                        placeholder="0.00"
                                        min="1"
                                        step="0.01"
                                        value="<c:choose><c:when test="${mode == 'edit'}">${tender.estimatedValue}</c:when><c:otherwise>${param.estimatedValue}</c:otherwise></c:choose>"
                                        required/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="form-label" for="closingDatetime">Submission Deadline <span style="color:var(--clr-danger)">*</span></label>
                                <input
                                    class="form-input"
                                    type="datetime-local"
                                    id="closingDatetime"
                                    name="closingDatetime"
                                    value="<c:choose><c:when test="${mode == 'edit'}"><fmt:formatDate value="${tender.closingDatetime}" pattern="yyyy-MM-dd'T'HH:mm"/></c:when><c:otherwise>${param.closingDatetime}</c:otherwise></c:choose>"
                                    required/>
                                <span class="form-hint">Server-side enforcement — suppliers cannot submit after this time.</span>
                            </div>
                        </div>

                        <!-- Notice PDF upload with size rule banner -->
                        <div class="form-group">
                            <label class="form-label" for="noticeFile">
                                Tender Notice Document (PDF, max 5MB)
                                <c:choose>
                                    <c:when test="${mode == 'create'}">
                                        <span style="color:var(--clr-danger)">*</span>
                                    </c:when>
                                    <c:otherwise>
                                        <span class="text-muted" style="font-weight:400;"> — leave empty to keep current file</span>
                                    </c:otherwise>
                                </c:choose>
                            </label>

                            <!-- File size rule banner -->
                            <div style="background:var(--clr-bg-elevated); border:1px solid var(--clr-border-subtle);
                                        border-radius:var(--radius-md); padding:var(--space-md);
                                        margin-bottom:var(--space-sm); font-size:0.82rem;">
                                <div style="display:flex; align-items:center; gap:8px; color:var(--clr-text-secondary);">
                                    <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"
                                         viewBox="0 0 24 24" style="flex-shrink:0; color:var(--clr-gold);">
                                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                                        <polyline points="14 2 14 8 20 8"/>
                                    </svg>
                                    Accepted format: <strong>PDF only</strong> &nbsp;·&nbsp;
                                    Maximum size: <strong style="color:var(--clr-gold);">5 MB</strong>
                                </div>
                                <div style="color:var(--clr-text-muted); margin-top:4px; font-size:0.78rem;">
                                    This document will be downloadable by all registered suppliers.
                                    Include full specifications, terms, and submission requirements.
                                </div>
                            </div>

                            <input
                                class="form-input"
                                type="file"
                                id="noticeFile"
                                name="noticeFile"
                                accept=".pdf"
                                onchange="checkPdfSize(this)"
                                style="padding:10px; cursor:pointer;"
                                <c:if test="${mode == 'create'}">required</c:if>/>

                            <!-- File feedback shown by JS -->
                            <div id="pdfStatus" style="margin-top:6px; font-size:0.82rem; display:none;"></div>

                            <c:if test="${mode == 'edit' && not empty tender.noticeFilePath}">
                                <div style="margin-top:8px; display:flex; align-items:center; gap:10px;">
                                    <span style="font-size:0.82rem; color:var(--clr-success);">✓ Current file on record.</span>
                                    <a href="${pageContext.request.contextPath}/files/download?type=notice&tenderId=${tender.tenderId}"
                                       target="_blank"
                                       class="btn btn-ghost"
                                       style="font-size:0.78rem; padding:5px 12px;">
                                        <svg width="13" height="13" fill="none" stroke="currentColor"
                                             stroke-width="2" viewBox="0 0 24 24">
                                            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                            <polyline points="7 10 12 15 17 10"/>
                                            <line x1="12" y1="15" x2="12" y2="3"/>
                                        </svg>
                                        Download Current PDF
                                    </a>
                                </div>
                            </c:if>
                        </div>

                        <div style="display:flex; gap:var(--space-md); margin-top:var(--space-lg); flex-wrap:wrap;">
                            <button type="submit" class="btn btn-primary btn--lg" id="tenderSubmitBtn">
                                <c:choose>
                                    <c:when test="${mode == 'edit'}">Save Changes</c:when>
                                    <c:otherwise>Create Tender</c:otherwise>
                                </c:choose>
                            </button>
                            <a href="${pageContext.request.contextPath}/officer/tenders" class="btn btn-ghost btn--lg">
                                Cancel
                            </a>
                        </div>

                    </form>
                </div>

            </div>
        </div>

        <script>
            const MAX_PDF_MB    = 5;
            const MAX_PDF_BYTES = MAX_PDF_MB * 1024 * 1024;

            /* ── PDF file size check ───────────────────────────────── */
            function checkPdfSize(input) {
                const errorBox  = document.getElementById('pdfSizeError');
                const errorMsg  = document.getElementById('pdfSizeMsg');
                const statusBox = document.getElementById('pdfStatus');
                const submitBtn = document.getElementById('tenderSubmitBtn');

                if (!input.files || input.files.length === 0) {
                    errorBox.style.display  = 'none';
                    statusBox.style.display = 'none';
                    submitBtn.disabled      = false;
                    return;
                }

                const file    = input.files[0];
                const sizeMB  = (file.size / (1024 * 1024)).toFixed(2);
                const lowerName = file.name.toLowerCase();
                const isPdf = lowerName.endsWith('.pdf');
                const isValid = file.size <= MAX_PDF_BYTES && isPdf;

                if (!isPdf) {
                    errorBox.style.display  = 'flex';
                    errorMsg.textContent    = 'Tender notice must be a PDF file.';
                    statusBox.style.display = 'block';
                    statusBox.style.color   = 'var(--clr-danger)';
                    statusBox.textContent   = '✗ ' + file.name + ' — unsupported file type.';
                    submitBtn.disabled      = true;
                    errorBox.scrollIntoView({ behavior: 'smooth', block: 'center' });
                } else if (!isValid) {
                    errorBox.style.display  = 'flex';
                    errorMsg.textContent    =
                        'Your file "' + file.name + '" is ' + sizeMB + ' MB. '
                        + 'The maximum allowed is ' + MAX_PDF_MB + ' MB. '
                        + 'Please compress the PDF or choose a smaller file.';
                    statusBox.style.display = 'block';
                    statusBox.style.color   = 'var(--clr-danger)';
                    statusBox.textContent   = '✗ ' + file.name + ' (' + sizeMB + ' MB) — exceeds 5 MB limit.';
                    submitBtn.disabled      = true;
                    errorBox.scrollIntoView({ behavior: 'smooth', block: 'center' });
                } else {
                    errorBox.style.display  = 'none';
                    statusBox.style.display = 'block';
                    statusBox.style.color   = 'var(--clr-success)';
                    statusBox.textContent   = '✓ ' + file.name + ' (' + sizeMB + ' MB) — ready to upload.';
                    submitBtn.disabled      = false;
                }
            }

            /* ── Form submit guard ─────────────────────────────────── */
            document.getElementById('tenderForm').addEventListener('submit', function(e) {
                const closing = document.getElementById('closingDatetime').value;
                if (closing && new Date(closing) <= new Date()) {
                    e.preventDefault();
                    alert('Closing date/time must be in the future.');
                    return;
                }
                // Re-check file requirements in case onchange was bypassed.
                const fileInput = document.getElementById('noticeFile');
                const isCreateMode = '${mode}' === 'create';
                if (isCreateMode && (!fileInput.files || fileInput.files.length === 0)) {
                    e.preventDefault();
                    alert('Please upload the tender notice PDF before creating the tender.');
                    return;
                }
                if (fileInput.files && fileInput.files.length > 0) {
                    const lowerName = fileInput.files[0].name.toLowerCase();
                    if (!lowerName.endsWith('.pdf') || fileInput.files[0].size > MAX_PDF_BYTES) {
                        e.preventDefault();
                        checkPdfSize(fileInput);
                    }
                }
            });
        </script>

    </body>
</html>